### ISSUE TITLE
【依頼】フリマアプリ挙動確認	

### ISSUE THREAD

**Issue by morimonchan** [morimonchan/furima-38403#15]
自身のフリマアプリのURL
https://furima-38403-2.herokuapp.com/

****************************************

Basic認証のIDとパスワード 
ID:            admin
password:2222

****************************************

出品者用のメールアドレスとパスワード
mail          aaa@aaa
password aaa111

****************************************

購入者用のメールアドレスとパスワード 
mail:           bbb@bbb
password:  bbb111

****************************************

**Comment by yusuketono** [comment]
@morimonchan さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
##### ユーザー管理機能
- [x] **ニックネームが必須であること**
6文字以下でなくてもニックネームを登録できるように修正しましょう。
![スクリーンショット 2022-10-10 9 37 24](https://user-images.githubusercontent.com/51428519/194786742-3f727eac-f1b0-44cc-bdc8-a808bde36998.png)

##### 商品出品機能
- [x] **カテゴリーは、「---、メンズ、レディース、ベビー・キッズ、インテリア・住まい・小物、本・音楽・ゲーム、おもちゃ・ホビー・グッズ、家電・スマホ・カメラ、スポーツ・レジャー、ハンドメイド、その他」の11項目が表示されること（--- は初期値として設定すること）**
「ハンドメイド、その他」の項目を「ハンドメイド」に修正しましょう。
![スクリーンショット 2022-10-10 9 44 02](https://user-images.githubusercontent.com/51428519/194786981-afde4ffb-cd1b-4502-90ca-562ec211763c.png)


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A
